### ISSUE TITLE
jq streaming

### ISSUE THREAD

**Issue by jpmckinney** [droquo/droquo.github.io#1]
In http://subtxt.in/library-data/2016/03/28/json_stream_jq you originally describe needing to stream the items in a `docs` array, but later in the post you are simply streaming the items in a top-level array, using `fromstream(1|truncate_stream(inputs))`.

To turn a deep array (e.g. inside `docs`) into a stream of items, you need to do something like https://stackoverflow.com/a/48786559/244258

**Comment by dogrdon** [comment]
@jpmckinney thanks for taking the time to dig in and suggest an improvement (it's been a little while since i've spent time with this post).

You're correct, but I think it's important to note (though I don't think I do this in the post at all) that the json input from the `.gz` bulk download files is different from the json supplied by the API, so the approach I used here, while maybe not the only or best way, works for the bulk downloads as the data is not nested in the same way (i.e., everything one would need is in the top-level array as you point out).

I'll try to update post to clear up that confusion at some point soon.

Thanks again.

d

**Comment by jpmckinney** [comment]
No worries - I had been looking for a way to stream a nested array and found your post during that search, and I eventually figured it out, so I thought I'd share back :)
